#' ---
#' title: PAF and attributable cases to diabetes
#'        As per the new systematic review of RR for diabetes in 2024
#' author: Mathieu Bastard
#' date: 26/06/2025
#' 
#' 
#' 
#' 

rm(list=ls())

suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(propagate))
library(here)

#Run Functions script
source(here('inc_mort/R code/fun.R'))

#Function to import db from GTB databases
source(here("import/load_gtb.R"))


m <- 1e5
yr <- 2024

yrsplit <- 2020

tb <- load_gtb("tb",convert_dots = FALSE)
cty <- load_gtb("cty",convert_dots = FALSE)
pop <- load_gtb("pop",convert_dots = FALSE)
grpmbr <- load_gtb("grpmbr",convert_dots = FALSE)
sdg <- load_gtb("sdg",convert_dots = FALSE)


#load last year estiamtes data
load(here('inc_mort/estimates2024/old.rda'))
old=copy(est)
rm(est)

#load data generated by previous scripts
load(here('inc_mort/analysis/est.rda'))

#load UNAIDS data
load(here('inc_mort/analysis/unaids.rda'))

vglohi <- Vectorize(glohi, c('ev', 'sd'))


# Prevalence of diabetes
# Downloaded from the WHO Global Health Observatory using script at ~/import/save_diabetes.R

load(here("data/gho/prev_diabetes_18plus.rda"))
setDT(diabetes)
setkey(diabetes, iso3, year)

diabetes <-
  merge(diabetes, pop[year==yr, .(iso3,
                              pop = e.pop.num,
                              adults.m = e.pop.m15plus,
                              adults.f = e.pop.f15plus,
                              adults = e.pop.15plus)], by = 'iso3')




# RR for diabetes, MA review in 2024
rr.dia <- c(1.6, (1.80 - 1.42) / 3.92)



# attributable fraction, propagating errors
#
paf2 <- function(pe, rr) {
  # @param pe proportion exposed: c(mean, sd)
  # @param rr relative risk: c(mean, sd)
  # @export
  require(propagate)
  
  DT <- cbind(pe, rr)
  EXPR <- expression(pe * (rr - 1) / (pe * (rr - 1) + 1))
  out <-
    propagate(
      expr = EXPR,
      data = DT,
      type = 'stat',
      do.sim = F,
      second.order = T
    )
  return(out)
}


out.dia <- diabetes[, {
  tmp = paf2(c(val/100, ((hi/100)-(lo/100))/3.92), rr.dia)$prop
  list(paf.dia = tmp[2],
       paf.dia.sd = tmp[4])
}, by = .(iso3)]


diabetes=merge(diabetes,out.dia,by="iso3")


diabetes=merge(diabetes,est[year==yr,.(iso3,inc,inc.sd)],by="iso3")

inc.dia <-
  diabetes[, prodXY(inc, paf.dia, inc.sd, paf.dia.sd), by = iso3]
setnames(inc.dia, c('iso3', 'inc.at.dia', 'inc.at.dia.sd'))


diabetes=merge(diabetes,inc.dia,by="iso3")

diabetes[, inc.at.dia.num := inc.at.dia * pop / m]

#Bounds
out <- diabetes[, vglohi(inc.at.dia.num, inc.at.dia.sd * pop / m)]
diabetes[, inc.at.dia.lo.num := out[1,]]
diabetes[, inc.at.dia.hi.num := out[2,]]

diabetes[,sums(inc.at.dia.num)]


diabetespaf=diabetes[,.(iso3,prev.dia.new=val, prev.dia.sd.new=(hi-lo)/3.92 ,paf.dia.new=paf.dia,paf.dia.sd.new=paf.dia.sd,inc.at.dia.num.new=inc.at.dia.num,inc.at.dia.lo.num.new=inc.at.dia.lo.num,inc.at.dia.hi.num.new=inc.at.dia.hi.num)]


# save
#
attr(diabetespaf, "timestamp") <- Sys.Date() #set date
save(diabetespaf, file = here('inc_mort/analysis/diabetes_new_att.rda'))
fwrite(diabetespaf, file = here(paste0('inc_mort/analysis/csv/diabetes_new_att.rda_', Sys.Date(), '.csv')))







