"""
Analyze PubMed abstract-extracted numeric mentions (exploratory screening aid).

Inputs (generated by `scripts/lit_search_pubmed.py`):
  - reports/pubmed_search_results.csv
  - reports/pubmed_percent_mentions.csv
  - reports/pubmed_numeric_mentions.csv
  - reports/pubmed_excluded.csv (optional)

Outputs:
  - reports/pubmed_numeric_mentions_by_pmid.csv
  - reports/pubmed_numeric_mentions_category_summary.csv
  - reports/pubmed_numeric_analysis.md
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterable

import pandas as pd


def classify_context(text: str) -> str:
    t = (text or "").lower()
    if not t.strip():
        return "unknown"

    if any(k in t for k in ["sensitivity", "specificity", "ppv", "npv", "auc", "accuracy"]):
        return "diagnostic_performance"
    if any(k in t for k in ["cured", "treatment completed", "death", "mortality", "loss to follow", "failure", "outcome"]):
        return "treatment_outcomes"
    if any(k in t for k in ["male", "female", "age", "years", "median", "interquartile", "hiv"]):
        return "demographics_comorbidity"
    if any(k in t for k in ["resistan", "rifamp", "isoniazid", "mdr", "xdr", "rr-tb", "pre-xdr"]):
        return "drug_resistance_profile"
    if any(k in t for k in ["prevalen", "inciden", "survey", "burden"]):
        return "epidemiology_burden"
    return "other"


def write_markdown_report(
    *,
    out_md: Path,
    df_search: pd.DataFrame,
    df_percent: pd.DataFrame,
    df_numeric: pd.DataFrame,
    df_excluded: pd.DataFrame | None,
    df_by_pmid: pd.DataFrame,
    df_cat: pd.DataFrame,
) -> None:
    total_search = len(df_search)
    total_percent_pmids = len(df_percent)
    total_numeric_mentions = len(df_numeric)
    excluded_n = len(df_excluded) if df_excluded is not None else None

    top_pmids = df_by_pmid.sort_values(["n_percents", "pmid"], ascending=[False, True]).head(10)
    top_cat = df_cat.sort_values(["mentions", "category"], ascending=[False, True])

    lines: list[str] = []
    lines.append("# PubMed Abstract Numeric Mentions (Exploratory)\n")
    lines.append("This report summarizes **automatically extracted numeric mentions** from PubMed abstracts.\n")
    lines.append("- These extracts are intended for **screening/triage**, not evidence synthesis.\n")
    lines.append("- Percent values may refer to demographics, diagnostics, outcomes, or non-India contexts.\n")
    lines.append("")
    lines.append("## Snapshot\n")
    lines.append(f"- Articles kept after India filter: {total_search}")
    if excluded_n is not None:
        lines.append(f"- Articles excluded by filter: {excluded_n}")
    lines.append(f"- Articles with ≥1 percent mention: {total_percent_pmids}")
    lines.append(f"- Total percent mentions (rows in `pubmed_numeric_mentions.csv`): {total_numeric_mentions}")
    lines.append("")
    lines.append("## Top Articles by Percent Mentions\n")
    lines.append("")
    lines.append("| pmid | year | n_percents | min | max | mean |")
    lines.append("|---:|:---:|---:|---:|---:|---:|")
    for _, r in top_pmids.iterrows():
        year = r.get("year", "")
        lines.append(
            f"| {int(r['pmid'])} | {year} | {int(r['n_percents'])} | {r['min']:.2f} | {r['max']:.2f} | {r['mean']:.2f} |"
        )
    lines.append("")
    lines.append("## Category Breakdown (Heuristic)\n")
    lines.append("")
    lines.append("| category | mentions | pmids |")
    lines.append("|---|---:|---:|")
    for _, r in top_cat.iterrows():
        lines.append(f"| {r['category']} | {int(r['mentions'])} | {int(r['pmids'])} |")
    lines.append("")
    lines.append("## Files\n")
    lines.append("- `reanalysis_project/reports/pubmed_search_results.csv`\n")
    lines.append("- `reanalysis_project/reports/pubmed_percent_mentions.csv`\n")
    lines.append("- `reanalysis_project/reports/pubmed_numeric_mentions.csv`\n")
    lines.append("- `reanalysis_project/reports/pubmed_numeric_mentions_by_pmid.csv`\n")
    lines.append("- `reanalysis_project/reports/pubmed_numeric_mentions_category_summary.csv`\n")
    if df_excluded is not None:
        lines.append("- `reanalysis_project/reports/pubmed_excluded.csv`\n")

    out_md.write_text("\n".join(lines), encoding="utf-8")


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    root = Path(__file__).resolve().parents[1]
    reports = root / "reports"
    p = argparse.ArgumentParser(description="Analyze extracted PubMed numeric mentions.")
    p.add_argument("--search-csv", default=str(reports / "pubmed_search_results.csv"))
    p.add_argument("--percent-csv", default=str(reports / "pubmed_percent_mentions.csv"))
    p.add_argument("--numeric-csv", default=str(reports / "pubmed_numeric_mentions.csv"))
    p.add_argument("--excluded-csv", default=str(reports / "pubmed_excluded.csv"))
    p.add_argument("--out-by-pmid-csv", default=str(reports / "pubmed_numeric_mentions_by_pmid.csv"))
    p.add_argument("--out-category-csv", default=str(reports / "pubmed_numeric_mentions_category_summary.csv"))
    p.add_argument("--out-md", default=str(reports / "pubmed_numeric_analysis.md"))
    return p.parse_args(argv)


def main() -> None:
    args = parse_args()
    df_search = pd.read_csv(args.search_csv)
    df_percent = pd.read_csv(args.percent_csv)
    df_numeric = pd.read_csv(args.numeric_csv)

    excluded_path = Path(args.excluded_csv)
    df_excluded = pd.read_csv(excluded_path) if excluded_path.exists() else None

    if not df_numeric.empty:
        df_numeric = df_numeric.copy()
        df_numeric["category"] = df_numeric["context_snippet"].fillna("").map(classify_context)

    # Per-PMID summary
    if df_percent.empty:
        df_by_pmid = pd.DataFrame(columns=["pmid", "year", "n_percents", "min", "max", "mean"])
    else:
        df_by_pmid = df_percent[["pmid", "n_percents", "min", "max", "mean"]].copy()
        df_by_pmid = df_by_pmid.merge(df_search[["pmid", "year"]], on="pmid", how="left")
        df_by_pmid = df_by_pmid[["pmid", "year", "n_percents", "min", "max", "mean"]]

    df_by_pmid.to_csv(args.out_by_pmid_csv, index=False)

    # Category summary
    if df_numeric.empty:
        df_cat = pd.DataFrame(columns=["category", "mentions", "pmids"])
    else:
        df_cat = (
            df_numeric.groupby("category", as_index=False)
            .agg(mentions=("percent", "size"), pmids=("pmid", "nunique"))
            .sort_values(["mentions", "category"], ascending=[False, True])
        )
    df_cat.to_csv(args.out_category_csv, index=False)

    write_markdown_report(
        out_md=Path(args.out_md),
        df_search=df_search,
        df_percent=df_percent,
        df_numeric=df_numeric,
        df_excluded=df_excluded,
        df_by_pmid=df_by_pmid,
        df_cat=df_cat,
    )
    print(f"Saved {args.out_md}")


if __name__ == "__main__":
    main()

